In [1]:
from tensorflow.keras.preprocessing.text import one_hot # library to one hot encode these sentences

In [2]:
sentences=sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
vocab_size=10000 #vocalbulary dictionary size

In [5]:
#method 1
onehot_repr=[one_hot(words,vocab_size)for words in sentences] 
print(onehot_repr)

[[6876, 6827, 6239, 3398], [6876, 6827, 6239, 4489], [6876, 1849, 6239, 2547], [64, 8681, 4831, 6206, 475], [64, 8681, 4831, 6206, 6922], [8287, 6876, 4805, 6239, 5748], [154, 9304, 1059, 6206]]


In [8]:
#method 2
onehot_repr2=[]
for sentence in sentences:
    encoded_sentence = one_hot(sentence, vocab_size)
    onehot_repr2.append(encoded_sentence)

In [9]:
print(onehot_repr2)

[[6876, 6827, 6239, 3398], [6876, 6827, 6239, 4489], [6876, 1849, 6239, 2547], [64, 8681, 4831, 6206, 475], [64, 8681, 4831, 6206, 6922], [8287, 6876, 4805, 6239, 5748], [154, 9304, 1059, 6206]]


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6876 6827 6239 3398]
 [   0    0    0    0 6876 6827 6239 4489]
 [   0    0    0    0 6876 1849 6239 2547]
 [   0    0    0   64 8681 4831 6206  475]
 [   0    0    0   64 8681 4831 6206 6922]
 [   0    0    0 8287 6876 4805 6239 5748]
 [   0    0    0    0  154 9304 1059 6206]]


In [13]:
dim=10

In [18]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.predict(embedded_docs) #Each sentence is one hot encoded using dim(10) features

1/1 [==============================] - 0s 84ms/step


2024-07-30 18:09:56.616711: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[-0.04012595,  0.00391046, -0.03334867, -0.01932571,
          0.01427511,  0.02332201, -0.00609485,  0.03578841,
         -0.03428417, -0.04016785],
        [-0.04012595,  0.00391046, -0.03334867, -0.01932571,
          0.01427511,  0.02332201, -0.00609485,  0.03578841,
         -0.03428417, -0.04016785],
        [-0.04012595,  0.00391046, -0.03334867, -0.01932571,
          0.01427511,  0.02332201, -0.00609485,  0.03578841,
         -0.03428417, -0.04016785],
        [-0.04012595,  0.00391046, -0.03334867, -0.01932571,
          0.01427511,  0.02332201, -0.00609485,  0.03578841,
         -0.03428417, -0.04016785],
        [ 0.00222214,  0.00763335,  0.04987539, -0.0290463 ,
          0.01832295,  0.02716095,  0.04074855, -0.00492972,
          0.03575378,  0.00832295],
        [ 0.03925445, -0.04708698,  0.01070999, -0.00896356,
         -0.04883293,  0.03354391,  0.00964629,  0.0369144 ,
         -0.00758257,  0.00646734],
        [-0.04848063, -0.00860914,  0.00095148,  0.0